[package]
name = "proxy-twister"
version = "1.0.0"
edition = "2024"
author = "Mikhail Lesin"

[dependencies]
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
